### ISSUE TITLE
Log out user

### ISSUE THREAD

**Issue by stenspanar** [Kirens/DAT256#101]
**As a** user **I want to** be able to log out **since** its hard to clear my cookies

# Tasks
* [ ] Lists all tasks (with id ex. #16) from potential break down

# Acceptance Criteria
* [ ] there should exist a button that allows the user to log out
* [ ] if logged out, the user should be presented with option to log in again

# Definition of done
* Code compiles
* Passes all tests
* Reviewer runs code on own machine
