### ISSUE TITLE
Menu system

### ISSUE THREAD

**Issue by DanielWillim** [Kirens/DAT256#102]
The point of this task is that we need a simple menu-system in order to navigate the app

This is a task of #18 

# Subtasks
* [ ] Able to navigate to the different pages of the app that you wont anturally land on
  * [ ] Leaderboard
  * [ ] When #101 is implemnted, a button to logout
  * [ ] Developermode
  * [ ] Be able to navigate back to the game
