### ISSUE TITLE
Merge components

### ISSUE THREAD

**Issue by stenspanar** [Kirens/DAT256#13]
The point of this task is to merge components so they work together.
This is a task of #6 that depends on #9 #10 #12

# Subtasks
* [ ] the user is presented with a question first
* [ ] when the question component signals a correct answer display the winning screen
* [ ] when the question component signals a wrong answer display the losing screen
