### ISSUE TITLE
Login to Account

### ISSUE THREAD

**Issue by MartinWendt** [Kirens/DAT256#32]
You need to be able to log in to your own account so your own score will be added to the leaderbords.

# Acceptance Criteria
* [x] Check that username and password match
* [x] Display passwords with ******
* [x] Only available if you are not logged in
* [ ] Stay logged in checkbox?
* [x] Login button
* [ ] Forgotten pasword/username button
* [x] Good errormessages
# Definition of done
* [ ] Code compiles
* [ ] ...
