### ISSUE TITLE
Quiz spel

### ISSUE THREAD

**Issue by MartinWendt** [Kirens/DAT256#5]
Spelet ska vara fult fungerande och engagerande.

# Acceptance Criteria
* [ ] Toplista för ledare
* [ ] Nytt spel skapas var 15e till 30e minut
* [ ] Tiden man får per fråga är välbalanserad
* [ ] Frågorna är många och shufflas väl

# Definition of done

**Comment by Kirens** [comment]
This is not really practical
