### ISSUE TITLE
Clean-up code base

### ISSUE THREAD

**Issue by DanielWillim** [Kirens/DAT256#76]
**As a** developer **I want to** have a clean codebase **since** this allows me to have a better overview of the code base

# Tasks
* [x] Lists all tasks (with id ex. #16) from potential break down

# Acceptance Criteria
* [x] All src-files that are not used should be removed

# Definition of done
* [x] Code compiles
* [x] Passes all tests
* [x] Reviewer runs code on own machine
  * [x] Reviewer 1
  * [ ] Reviewer 2
