### ISSUE TITLE
New Game Over Screen

### ISSUE THREAD

**Issue by DanielWillim** [Kirens/DAT256#78]
**As a** user **I want a** game over screen that follows the app desing **since** this looks better and I like nice things ;) 

# Tasks
* [x] Lists all tasks (with id ex. #16) from potential break down

# Acceptance Criteria
* [ ] Create a new Game Over screen with the same desing patterns as the rest of the app
* [ ] The User should be able to start a new game and view how many point he/she got

# Definition of done
* [ ] Code compiles
* [ ] Passes all tests
* [ ] Reviewer runs code on own machine
  * [ ] Reviewer 1
  * [ ] Reviewer 2
