### ISSUE TITLE
Win/Fail screen cleanup

### ISSUE THREAD

**Issue by DanielWillim** [Kirens/DAT256#79]
**As a** user **I want to** have a pretty app **since** I will be more likely to use it

# Tasks
* [x] Lists all tasks (with id ex. #16) from potential break down

# Acceptance Criteria
* [ ] Time left should be rounded to whole seconds as in the "Game Screen" 
* [ ] Look over the rest of the design and evaluate what should be left
* [ ] Implenet suggested changes

# Definition of done
* [ ] Code compiles
* [ ] Passes all tests
* [ ] Reviewer runs code on own machine
  * [ ] Reviewer 1
  * [ ] Reviewer 2
