### ISSUE TITLE
Know Git

### ISSUE THREAD

**Issue by elinsilver** [Kirens/DAT256#8]
The point of this task is that everyone should know our git workflow.

# Tasks
* [ ] Write down the workflow
* [ ] Create instructions

* [ ] Veta hur du pushar, pullar, och commitar kod till en specifik branch
* [ ] Vet hur du byter till en annan branch, checkout
* [ ] Pull request
* [ ] Merga
* [ ] Review
* [ ] meta branchen - Markdown, social contract

* [ ] Every developer needs a git set up 
* * [ ] Anna
* * [x] Elin
* * [ ] Fanny
* * [ ] Malin
* * [ ] Martin
* * [x] Daniel
* * [ ] Erik
* * [x] Samuel

* [ ] Try the instructions 
* * [ ] Anna
* * [ ] Elin
* * [ ] Fanny
* * [ ] Malin
* * [ ] Martin
* * [x] Daniel
* * [ ] Erik
* * [ ] Samuel
