### ISSUE TITLE
Mobilanpassning av sidan

### ISSUE THREAD

**Issue by stenspanar** [Kirens/DAT256#86]
**As a** user **I want to** be able to play the game in phone **since** the phone is what I will priobably have available to play with.

# Tasks
* [ ] Lists all tasks (with id ex. #16) from potential break down

# Acceptance Criteria
* [x] The site of the game is possible to use on at least one cellphone

# Definition of done
* [ ] Code compiles
* [ ] Passes all tests
* [ ] Reviewer runs code on own machine
  * [ ] Reviewer 1
  * [ ] Reviewer 2
