### ISSUE TITLE
Ticket storage

### ISSUE THREAD

**Issue by Kirens** [Kirens/DAT256#88]
**As a** user **I don't want to** enter my ticket number each time I launch the app **since** I want to start playing the game faster.

# Tasks
* [x] #90 Auth implementation
* [x] #91 Database abstration
* [x] #92 Store ticket
* [x] #93 Remove ticket

# Acceptance Criteria
* [ ] When I open the app I can sign in, then I enter my ticket number, then start the game.
* [ ] If I open the app later at the same or another device I will not have to enter my ticket number after signing in.
* [ ] I should be able to change or remove my ticket.

# Definition of done
* [ ] Code compiles
* [ ] Passes all tests
* [ ] Reviewer runs code on own machine
  * [ ] Reviewer 1
  * [ ] Reviewer 2
