### ISSUE TITLE
Konsekvent UI

### ISSUE THREAD

**Issue by XP64** [Kirens/DAT256#89]
**As a** user **I want to** to use the same design elements and intuitive design all over the application **since** it allows me to use the application hassle-free. 

# Tasks
* [ ] Lists all tasks (with id ex. #16) from potential break down

# Acceptance Criteria
* [ ] Suggest a design that includes
  * [ ] All pages should use the same design
  * [ ] All buttons, links and such content should use their own design
  * [ ] The UI should be intuitive and hassle-free
  * [ ] The UI should be similar to the mobile version
* [ ] Create a user Story with impementaiton of the suggested changes

# Definition of done
* [ ] Code compiles
* [ ] Passes all tests
* [ ] Reviewer runs code on own machine
  * [ ] Reviewer 1
  * [ ] Reviewer 2
