### ISSUE TITLE
User manual for database

### ISSUE THREAD

**Issue by stenspanar** [Kirens/DAT256#99]
**As a** a developer **I want to** how to use databases **since** I need to use databases in order to create value 

# Tasks
* [ ] Lists all tasks (with id ex. #16) from potential break down

# Acceptance Criteria
* [ ] there exists documentation that describes how I use the database
* [ ] how to get value from db
* [ ] How to save a value to db

# Definition of done
* Code compiles
* Passes all tests
* Reviewer runs code on own machine
